services:
  opensearch:
    image: opensearchproject/opensearch:3.1.0
    container_name: govdoc-opensearch
    environment:
      # Cluster configuration
      - cluster.name=govdoc-cluster
      - node.name=govdoc-node1
      - discovery.type=single-node
      # Memory settings for development
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      # Security configuration - required for OpenSearch 3.1
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      # Data persistence
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200" # REST API
      - "9600:9600" # Performance Analyzer
    networks:
      - opensearch-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -k -u admin:${OPENSEARCH_INITIAL_ADMIN_PASSWORD} https://localhost:9200/_cluster/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.1.0
    container_name: govdoc-opensearch-dashboards
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      # Connect to OpenSearch node
      - OPENSEARCH_HOSTS=["https://opensearch:9200"]
    depends_on:
      opensearch:
        condition: service_healthy
    networks:
      - opensearch-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  opensearch-data:
    driver: local

networks:
  opensearch-net:
    driver: bridge
